import z from 'zod'

/**
 * Zod schema for an SRD creature entry.
 *
 * Extends the base creature shape with `size` and `category` fields that
 * capture the physical size category and monster type from the 5.1 SRD.
 * Initiative is always `'roll'` (DEX modifier) for SRD creatures.
 */
export const srdCreatureValidator = z.object({
  id: z.string(),
  name: z.string().min(1),
  initiativeType: z.enum(['fixed', 'roll']),
  initiative: z.number().int(),
  hp: z.number().int().nonnegative(),
  size: z.enum(['Tiny', 'Small', 'Medium', 'Large', 'Huge', 'Gargantuan']),
  category: z.string().min(1),
  categoryIds: z.array(z.string()),
})

export type SrdCreature = z.infer<typeof srdCreatureValidator>

/**
 * All creature statblocks parsed from the 5.1 SRD (CC-BY-4.0).
 *
 * Each entry's `initiative` is the DEX modifier (used with `initiativeType: 'roll'`
 * so a d20 is rolled and added at combat start). `categoryIds` reference the
 * pre-generated IDs in `DEFAULT_CATEGORIES` from `src/db/seeds/categories.ts`.
 */
export const SRD_CREATURES: SrdCreature[] = [
  {
    id: 'Pke2alpva1pKZeqHMZeAm',
    name: 'Aboleth',
    initiativeType: 'roll',
    initiative: -1,
    hp: 135,
    size: 'Large',
    category: 'Aberration',
    categoryIds: ['hL6Lx5RYOj_ViMtZD2oI3'],
  },
  {
    id: 'hWfbbibHL07x_ZNueLQh0',
    name: 'Deva',
    initiativeType: 'roll',
    initiative: 4,
    hp: 136,
    size: 'Medium',
    category: 'Celestial',
    categoryIds: ['aWqvZp9oborYGfWKSl8Uq'],
  },
  {
    id: 'BzVkz5OkAbohWU56QSoT8',
    name: 'Planetar',
    initiativeType: 'roll',
    initiative: 5,
    hp: 200,
    size: 'Large',
    category: 'Celestial',
    categoryIds: ['aWqvZp9oborYGfWKSl8Uq'],
  },
  {
    id: 'jb0Zsaf33TMYf2oP6DCiR',
    name: 'Solar',
    initiativeType: 'roll',
    initiative: 6,
    hp: 243,
    size: 'Large',
    category: 'Celestial',
    categoryIds: ['aWqvZp9oborYGfWKSl8Uq'],
  },
  {
    id: 'AK6YgaY16RjLX-Y2akPwQ',
    name: 'Animated Armor',
    initiativeType: 'roll',
    initiative: 0,
    hp: 33,
    size: 'Medium',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: '3XxesWrOIrQNrl4QWE7RV',
    name: 'Flying Sword',
    initiativeType: 'roll',
    initiative: 2,
    hp: 17,
    size: 'Small',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: 'xoH0lMeEw-dsoCbZeAXPz',
    name: 'Rug of Smothering',
    initiativeType: 'roll',
    initiative: 2,
    hp: 33,
    size: 'Large',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: '9QMwArAf7TBF6j3vWiTql',
    name: 'Ankheg',
    initiativeType: 'roll',
    initiative: 0,
    hp: 39,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'IH6p3VyfLyJZr4WOE6g5H',
    name: 'Azer',
    initiativeType: 'roll',
    initiative: 1,
    hp: 39,
    size: 'Medium',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'DP1Bn_4YfSvqdVB0OCowQ',
    name: 'Basilisk',
    initiativeType: 'roll',
    initiative: -1,
    hp: 52,
    size: 'Medium',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: '2VVh4lNqaOOIDtxQ5pqjC',
    name: 'Behir',
    initiativeType: 'roll',
    initiative: 3,
    hp: 168,
    size: 'Huge',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'eWhMu1_PgEResdEa5kd5d',
    name: 'Bugbear',
    initiativeType: 'roll',
    initiative: 2,
    hp: 27,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'WrbcInMXirB1kab_T0daQ',
    name: 'Bulette',
    initiativeType: 'roll',
    initiative: 0,
    hp: 94,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'CzxUc-yQXHGoyxR6pCafi',
    name: 'Centaur',
    initiativeType: 'roll',
    initiative: 2,
    hp: 45,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'zW-PaYnHQEJvUk_WGAdC5',
    name: 'Chimera',
    initiativeType: 'roll',
    initiative: 0,
    hp: 114,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'kuVingW47-a9IQUlJycV5',
    name: 'Chuul',
    initiativeType: 'roll',
    initiative: 0,
    hp: 93,
    size: 'Large',
    category: 'Aberration',
    categoryIds: ['hL6Lx5RYOj_ViMtZD2oI3'],
  },
  {
    id: '_fAjPXFUGfiZ8bPk2mOZL',
    name: 'Cloaker',
    initiativeType: 'roll',
    initiative: 2,
    hp: 78,
    size: 'Large',
    category: 'Aberration',
    categoryIds: ['hL6Lx5RYOj_ViMtZD2oI3'],
  },
  {
    id: 'E2Go3bpuOBnM4qD3LQFn8',
    name: 'Cockatrice',
    initiativeType: 'roll',
    initiative: 1,
    hp: 27,
    size: 'Small',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: '0Nt07fZngFMUHaLYkiU9t',
    name: 'Couatl',
    initiativeType: 'roll',
    initiative: 5,
    hp: 97,
    size: 'Medium',
    category: 'Celestial',
    categoryIds: ['aWqvZp9oborYGfWKSl8Uq'],
  },
  {
    id: 'J3U4q_uRSYIe9IiKCO7pg',
    name: 'Darkmantle',
    initiativeType: 'roll',
    initiative: 1,
    hp: 22,
    size: 'Small',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'gfvRXVxaWQ0zwb0M-k8xK',
    name: 'Balor',
    initiativeType: 'roll',
    initiative: 2,
    hp: 262,
    size: 'Huge',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'gtf6pDbszVpF4fBU25dCf',
    name: 'Dretch',
    initiativeType: 'roll',
    initiative: 0,
    hp: 18,
    size: 'Small',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'AWvDiNeVtG-clmbrjUTNZ',
    name: 'Glabrezu',
    initiativeType: 'roll',
    initiative: 2,
    hp: 157,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'hNRSs66t-zlpLB0x2ccDi',
    name: 'Hezrou',
    initiativeType: 'roll',
    initiative: 3,
    hp: 136,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'F_wdkMVywph7_1_C0hxha',
    name: 'Marilith',
    initiativeType: 'roll',
    initiative: 5,
    hp: 189,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'XQBdcmJaDiUUllklrKu3Q',
    name: 'Nalfeshnee',
    initiativeType: 'roll',
    initiative: 0,
    hp: 184,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'xPYJ6dgyy_fz20PGW2HX2',
    name: 'Quasit',
    initiativeType: 'roll',
    initiative: 3,
    hp: 7,
    size: 'Tiny',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'ktbZGD2EhVZpEBFxajmIL',
    name: 'Vrock',
    initiativeType: 'roll',
    initiative: 2,
    hp: 104,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'iPWu5JoFhUIgVxVI0y218',
    name: 'Barbed Devil',
    initiativeType: 'roll',
    initiative: 3,
    hp: 110,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: '1dURlSn8uhQunnyDVjmQT',
    name: 'Bearded Devil',
    initiativeType: 'roll',
    initiative: 2,
    hp: 52,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'qMNd38EpcPpY1UbWtRKI9',
    name: 'Bone Devil',
    initiativeType: 'roll',
    initiative: 3,
    hp: 142,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'artiggnJaNdIPbzhKissQ',
    name: 'Chain Devil',
    initiativeType: 'roll',
    initiative: 2,
    hp: 85,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'csASyV14mzoqAj8g3Ioye',
    name: 'Erinyes',
    initiativeType: 'roll',
    initiative: 3,
    hp: 153,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'NeUbIGMK1b-KmXeca0rae',
    name: 'Horned Devil',
    initiativeType: 'roll',
    initiative: 3,
    hp: 178,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'vxES8VCXhi1OahFHCO1VU',
    name: 'Ice Devil',
    initiativeType: 'roll',
    initiative: 2,
    hp: 180,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'EnMCEdWeG5sdzMiKhy1aL',
    name: 'Imp',
    initiativeType: 'roll',
    initiative: 3,
    hp: 10,
    size: 'Tiny',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'mqO3eKY_Cmn-aPb6QxYo8',
    name: 'Lemure',
    initiativeType: 'roll',
    initiative: -3,
    hp: 13,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: '8X_8H62vQx9i6NeVuaKt1',
    name: 'Pit Fiend',
    initiativeType: 'roll',
    initiative: 2,
    hp: 300,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'IXZvORHNVH0NXApE6t43u',
    name: 'Plesiosaurus',
    initiativeType: 'roll',
    initiative: 2,
    hp: 68,
    size: 'Large',
    category: 'Beast',
    categoryIds: ['5Bp7ldzDgpP_OafAMj9pL'],
  },
  {
    id: 'FPzYToMxOuHchc5Ili_a7',
    name: 'Triceratops',
    initiativeType: 'roll',
    initiative: -1,
    hp: 95,
    size: 'Huge',
    category: 'Beast',
    categoryIds: ['5Bp7ldzDgpP_OafAMj9pL'],
  },
  {
    id: 'xopYiYwPpIv2P-7KqUP3y',
    name: 'Tyrannosaurus Rex',
    initiativeType: 'roll',
    initiative: 0,
    hp: 136,
    size: 'Huge',
    category: 'Beast',
    categoryIds: ['5Bp7ldzDgpP_OafAMj9pL'],
  },
  {
    id: '_KO35ZRJSMKJ2B2ET-yXS',
    name: 'Doppelganger',
    initiativeType: 'roll',
    initiative: 4,
    hp: 52,
    size: 'Medium',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'p3iiCJDmDUkL7IAix_xmF',
    name: 'Ancient Black Dragon',
    initiativeType: 'roll',
    initiative: 2,
    hp: 367,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'kc5bkrfHhjh2F4wfrmUM6',
    name: 'Adult Black Dragon',
    initiativeType: 'roll',
    initiative: 2,
    hp: 195,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'VxSGaZ34NBPY-jcf7xXkw',
    name: 'Young Black Dragon',
    initiativeType: 'roll',
    initiative: 2,
    hp: 127,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'Wru6k9467wWiZUs6yQ67I',
    name: 'Black Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 2,
    hp: 33,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'hSxq5RR4PG6nIIXbPK-c-',
    name: 'Blue Dragon Ancient Blue Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 481,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'Hfmv7gmJcH5Cnv3tN9M16',
    name: 'Adult Blue Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 225,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'LPcvD8uCeUoI7W_wDTTLM',
    name: 'Young Blue Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 152,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'oXXQo7zQ-UfuAWEaUU37S',
    name: 'Blue Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 0,
    hp: 52,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'SbBDCSTOyYvFwx2jsKQ5Z',
    name: 'Ancient Green Dragon',
    initiativeType: 'roll',
    initiative: 1,
    hp: 385,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'PjNR8arqZx31SeLXAZ7ee',
    name: 'Adult Green Dragon',
    initiativeType: 'roll',
    initiative: 1,
    hp: 207,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: '03Q5MZBzsp45WHq_8THzN',
    name: 'Young Green Dragon',
    initiativeType: 'roll',
    initiative: 1,
    hp: 136,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'PisuhwSWzkQY7n-SCvULN',
    name: 'Green Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 1,
    hp: 38,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'GcWw7JlSllhTPp-R2vFNt',
    name: 'Ancient Red Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 546,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: '5emQHez3XbwTdWMfRbMeX',
    name: 'Adult Red Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 256,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'nCYwYU-kf_EAuGc4a8kRt',
    name: 'Young Red Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 178,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'howp-njmk5cKxoIZz4YQg',
    name: 'Red Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 0,
    hp: 75,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'HIX3W2NpS7RDPvXpn-WRm',
    name: 'Ancient White Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 333,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'f2ZqZOlCpWXvSaUG0M83H',
    name: 'Adult White Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 200,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'mC0ksDN_MyUZyz8vU6u5q',
    name: 'Young White Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 133,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'GRmk7zXpwH3PnTUJ-DseJ',
    name: 'White Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 0,
    hp: 32,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'Kiak-Jx8HmQTNcSUFtOb6',
    name: 'Ancient Brass Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 297,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'RRCjDW4K60mhCk7OO-bPF',
    name: 'Adult Brass Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 172,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'TjQW1BCwz3bU1l9qJbrHQ',
    name: 'Young Brass Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 110,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'n3QRkUThfLuq-sspC4k4v',
    name: 'Brass Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 0,
    hp: 16,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'kt6yR4MdnG3DaW_92Ajl7',
    name: 'Ancient Bronze Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 444,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: '7exoCEYrYSQviGHl5upoT',
    name: 'Adult Bronze Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 212,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'HYsdxoPC-DOibXKPxuDgZ',
    name: 'Young Bronze Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 142,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'yOs56G8MmG2FXo30q5fqL',
    name: 'Bronze Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 0,
    hp: 32,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: '1BQWEQVhfbktQOsC_MQEe',
    name: 'Ancient Copper Dragon',
    initiativeType: 'roll',
    initiative: 1,
    hp: 350,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'Px5-g3QPlcjh1ee-U7H63',
    name: 'Adult Copper Dragon',
    initiativeType: 'roll',
    initiative: 1,
    hp: 184,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'QDMfdaY3DdvQHB-9G0cRE',
    name: 'Young Copper Dragon',
    initiativeType: 'roll',
    initiative: 1,
    hp: 119,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'vJAK6NB0E-c9GWDHGZNK5',
    name: 'Copper Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 1,
    hp: 22,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'AtwMY91S-bvqvHC7vckVz',
    name: 'Ancient Gold Dragon',
    initiativeType: 'roll',
    initiative: 2,
    hp: 546,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: '4PvU1zP4eD-XJiLk0A5dD',
    name: 'Adult Gold Dragon',
    initiativeType: 'roll',
    initiative: 2,
    hp: 256,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: '49WrL_83KUH3ulCTdbUje',
    name: 'Young Gold Dragon',
    initiativeType: 'roll',
    initiative: 2,
    hp: 178,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'ofxLGZSc1qjUfTG1vaN5L',
    name: 'Gold Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 2,
    hp: 60,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'GQMKrxLqVGYrGydW0fQMT',
    name: 'Ancient Silver Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 487,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'ZtF3sMWoDwpKgt5eldrik',
    name: 'Adult Silver Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 243,
    size: 'Huge',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: '9d2AdmqhYjFzybCHV58_X',
    name: 'Young Silver Dragon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 168,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'jKwFHRejW0TrDPgnwEtvn',
    name: 'Silver Dragon Wyrmling',
    initiativeType: 'roll',
    initiative: 0,
    hp: 45,
    size: 'Medium',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'WPflYjAegrKpQMziL8wi0',
    name: 'Dragon Turtle',
    initiativeType: 'roll',
    initiative: 0,
    hp: 341,
    size: 'Gargantuan',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'uGHW_T16elTLeg6umiAd4',
    name: 'Drider',
    initiativeType: 'roll',
    initiative: 3,
    hp: 123,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'yqe8HM1bPfccuqH84wM_i',
    name: 'Dryad',
    initiativeType: 'roll',
    initiative: 1,
    hp: 22,
    size: 'Medium',
    category: 'Fey',
    categoryIds: ['2GxyUQ21MGpzXIb50xxko'],
  },
  {
    id: 'L_mjBsBdb1kpMI8BtaJkY',
    name: 'Duergar',
    initiativeType: 'roll',
    initiative: 0,
    hp: 26,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'hHp_4_USE0hfC9d0Kt6lg',
    name: 'Air Elemental',
    initiativeType: 'roll',
    initiative: 5,
    hp: 90,
    size: 'Large',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'pBcSD8dymfvOC0-Hsc53S',
    name: 'Earth Elemental',
    initiativeType: 'roll',
    initiative: -1,
    hp: 126,
    size: 'Large',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: '0KBddrN-2jk1xEt2r6Ge4',
    name: 'Fire Elemental',
    initiativeType: 'roll',
    initiative: 3,
    hp: 102,
    size: 'Large',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'P2NEHYBdDCgpy6cNkcmeo',
    name: 'Water Elemental',
    initiativeType: 'roll',
    initiative: 2,
    hp: 114,
    size: 'Large',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'jp80j2apEJ6K16qDH1wzY',
    name: 'Elf, Drow',
    initiativeType: 'roll',
    initiative: 2,
    hp: 13,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'oi8k6dYShfUOvFVj2hPZh',
    name: 'Ettercap',
    initiativeType: 'roll',
    initiative: 2,
    hp: 44,
    size: 'Medium',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'B90T-wB0AkgB61Yp_J30Y',
    name: 'Ettin',
    initiativeType: 'roll',
    initiative: -1,
    hp: 85,
    size: 'Large',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'UWFvkWhErROCNLQSoJ77R',
    name: 'Shrieker',
    initiativeType: 'roll',
    initiative: -5,
    hp: 13,
    size: 'Medium',
    category: 'Plant',
    categoryIds: ['CCPdjktUPMbqrwM6x7Z1B'],
  },
  {
    id: 'Mabnhf7vhePhBT06vpMNf',
    name: 'Violet Fungus',
    initiativeType: 'roll',
    initiative: -5,
    hp: 18,
    size: 'Medium',
    category: 'Plant',
    categoryIds: ['CCPdjktUPMbqrwM6x7Z1B'],
  },
  {
    id: '5LXitIPr0XTuh2t38FUyZ',
    name: 'Gargoyle',
    initiativeType: 'roll',
    initiative: 0,
    hp: 52,
    size: 'Medium',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: '3EMZ-zrNKLgw3xc3YAPPL',
    name: 'Djinni',
    initiativeType: 'roll',
    initiative: 2,
    hp: 161,
    size: 'Large',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: '72gOscVUVDr0BuBfY7ZuW',
    name: 'Efreeti',
    initiativeType: 'roll',
    initiative: 1,
    hp: 200,
    size: 'Large',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'V3HNgBSDzNCxPfWyrM-GO',
    name: 'Ghost',
    initiativeType: 'roll',
    initiative: 1,
    hp: 45,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'NO6Y4HQxUv6FMD3bn6Zo_',
    name: 'Ghast',
    initiativeType: 'roll',
    initiative: 3,
    hp: 36,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: '-MUi2tk7gMsERtXfh-ZjU',
    name: 'Ghoul',
    initiativeType: 'roll',
    initiative: 2,
    hp: 22,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'nsgufUJqh5N6V2o_OPWwf',
    name: 'Cloud Giant',
    initiativeType: 'roll',
    initiative: 0,
    hp: 200,
    size: 'Huge',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'MAmNl5p_hMlVmq5aMIcHR',
    name: 'Fire Giant',
    initiativeType: 'roll',
    initiative: -1,
    hp: 162,
    size: 'Huge',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'LRNRq8xAr6j99kuIzuLkF',
    name: 'Frost Giant',
    initiativeType: 'roll',
    initiative: -1,
    hp: 138,
    size: 'Huge',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'MZZH1BNjEmbHeR6NYmFFg',
    name: 'Hill Giant',
    initiativeType: 'roll',
    initiative: -1,
    hp: 105,
    size: 'Huge',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'fdh5BV2H55I2LSKNK-qeA',
    name: 'Stone Giant',
    initiativeType: 'roll',
    initiative: 2,
    hp: 126,
    size: 'Huge',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'Ef0gTdM9EPkTjyRXy3ADi',
    name: 'Storm Giant',
    initiativeType: 'roll',
    initiative: 2,
    hp: 230,
    size: 'Huge',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: '75kSgSEb7_arcyLX_R0lG',
    name: 'Gibbering Mouther',
    initiativeType: 'roll',
    initiative: -1,
    hp: 67,
    size: 'Medium',
    category: 'Aberration',
    categoryIds: ['hL6Lx5RYOj_ViMtZD2oI3'],
  },
  {
    id: 'X3AKlYujMtBJisQVjDY_1',
    name: 'Gnoll',
    initiativeType: 'roll',
    initiative: 1,
    hp: 22,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'uhPBhG1jdMRRWzQ1AEc2d',
    name: 'Gnome, Deep (Svirfneblin)',
    initiativeType: 'roll',
    initiative: 2,
    hp: 16,
    size: 'Small',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'RgAvxxVzUB8K8J3h2cFQq',
    name: 'Goblin',
    initiativeType: 'roll',
    initiative: 2,
    hp: 7,
    size: 'Small',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'V64YQUlnmjJWyY0LF_Bci',
    name: 'Clay Golem',
    initiativeType: 'roll',
    initiative: -1,
    hp: 133,
    size: 'Large',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: 'p7Pja-y4MyCOhnrGcPjZy',
    name: 'Flesh Golem',
    initiativeType: 'roll',
    initiative: -1,
    hp: 93,
    size: 'Medium',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: 'IDk4CnJiuej0Z4Qm5P9DM',
    name: 'Iron Golem',
    initiativeType: 'roll',
    initiative: -1,
    hp: 210,
    size: 'Large',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: 'JjaCeJmL2DqMxJDGDLNnN',
    name: 'Stone Golem',
    initiativeType: 'roll',
    initiative: -1,
    hp: 178,
    size: 'Large',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: 'JnjbgWyY5z-rM-y8QwyVF',
    name: 'Gorgon',
    initiativeType: 'roll',
    initiative: 0,
    hp: 114,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'pzZ8pH7BpkT8HbtigBwX4',
    name: 'Grick',
    initiativeType: 'roll',
    initiative: 2,
    hp: 27,
    size: 'Medium',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: '-JMry97nnkSFE4VN8fBJ7',
    name: 'Griffon',
    initiativeType: 'roll',
    initiative: 2,
    hp: 59,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'HbGL74ur9wp3s94zIv9gY',
    name: 'Grimlock',
    initiativeType: 'roll',
    initiative: 1,
    hp: 11,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'eWCiBxJbXAC091-ekpQbK',
    name: 'Green Hag',
    initiativeType: 'roll',
    initiative: 1,
    hp: 82,
    size: 'Medium',
    category: 'Fey',
    categoryIds: ['2GxyUQ21MGpzXIb50xxko'],
  },
  {
    id: 'KfMr2kIRXy56-B5rS0Mgu',
    name: 'Night Hag',
    initiativeType: 'roll',
    initiative: 2,
    hp: 112,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'hRNjOOop4zYm4Njx3CF1s',
    name: 'Sea Hag',
    initiativeType: 'roll',
    initiative: 1,
    hp: 52,
    size: 'Medium',
    category: 'Fey',
    categoryIds: ['2GxyUQ21MGpzXIb50xxko'],
  },
  {
    id: 'oSkc25ok7qs7nWy_YBNP1',
    name: 'Half--Red Dragon Veteran',
    initiativeType: 'roll',
    initiative: 1,
    hp: 65,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'YqrZcbjiqhK664CdYlabE',
    name: 'Harpy',
    initiativeType: 'roll',
    initiative: 1,
    hp: 38,
    size: 'Medium',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: '3gXCsG_KwEO-DS7gzVAbj',
    name: 'Hell Hound',
    initiativeType: 'roll',
    initiative: 1,
    hp: 45,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: '6Mo3QLcw7QhPpGpqqG6tD',
    name: 'Hippogriff',
    initiativeType: 'roll',
    initiative: 1,
    hp: 19,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'Qlolr6GYo4J5r_s3XqnvG',
    name: 'Hobgoblin',
    initiativeType: 'roll',
    initiative: 1,
    hp: 11,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'EoOAqjcWVUeobTLuanMWh',
    name: 'Homunculus',
    initiativeType: 'roll',
    initiative: 2,
    hp: 5,
    size: 'Tiny',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: 'fOLD648YiZDxoBqkhgpHH',
    name: 'Hydra',
    initiativeType: 'roll',
    initiative: 1,
    hp: 172,
    size: 'Huge',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'yunM7haJ6Cqv3M8wh_RRU',
    name: 'Invisible Stalker',
    initiativeType: 'roll',
    initiative: 4,
    hp: 104,
    size: 'Medium',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: '9Ol5bDK4PzRmPpyTSCih9',
    name: 'Kobold',
    initiativeType: 'roll',
    initiative: 2,
    hp: 5,
    size: 'Small',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'pc25Joc1UwFewDypqbXXT',
    name: 'Kraken',
    initiativeType: 'roll',
    initiative: 0,
    hp: 472,
    size: 'Gargantuan',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'OAKHIRooHY4a-vV-MXkya',
    name: 'Lamia',
    initiativeType: 'roll',
    initiative: 1,
    hp: 97,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: '3VXKXtsaZgxFzN2_OGODW',
    name: 'Lich',
    initiativeType: 'roll',
    initiative: 3,
    hp: 135,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'jEY-esfz89IjJ4cCz2eMr',
    name: 'Lizardfolk',
    initiativeType: 'roll',
    initiative: 0,
    hp: 22,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'OY6t5jvE57wT0FDrQixQH',
    name: 'Werebear',
    initiativeType: 'roll',
    initiative: 0,
    hp: 135,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'LaFydX-K4RpVo0nTYp4GI',
    name: 'Wereboar',
    initiativeType: 'roll',
    initiative: 0,
    hp: 78,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'bo_ohdkSUnuT8TkCqfhh1',
    name: 'Wererat',
    initiativeType: 'roll',
    initiative: 2,
    hp: 33,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'Kf-aYn9KgvtmVGfRpS6m7',
    name: 'Weretiger',
    initiativeType: 'roll',
    initiative: 2,
    hp: 120,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'uwaV1OW3lIXAjssEMt-b8',
    name: 'Werewolf',
    initiativeType: 'roll',
    initiative: 1,
    hp: 58,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: '84I-rIcvcheUq9yreQ3eG',
    name: 'Magmin',
    initiativeType: 'roll',
    initiative: 2,
    hp: 9,
    size: 'Small',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'Nq5ZgOvhcF6AVWsauqgtV',
    name: 'Manticore',
    initiativeType: 'roll',
    initiative: 3,
    hp: 68,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'Lx0zNkkybhzLwum9_0IRU',
    name: 'Medusa',
    initiativeType: 'roll',
    initiative: 2,
    hp: 127,
    size: 'Medium',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'zxDOXGQdGd7uRqMQLW12-',
    name: 'Dust Mephit',
    initiativeType: 'roll',
    initiative: 2,
    hp: 17,
    size: 'Small',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'oh9QGsFuWlZl7zffqHVUa',
    name: 'Ice Mephit',
    initiativeType: 'roll',
    initiative: 1,
    hp: 21,
    size: 'Small',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'PcvjioTApl1W4KjYWmyFJ',
    name: 'Magma Mephit',
    initiativeType: 'roll',
    initiative: 1,
    hp: 22,
    size: 'Small',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'rhmqRxTag4MjbKrAuxAKn',
    name: 'Steam Mephit',
    initiativeType: 'roll',
    initiative: 0,
    hp: 21,
    size: 'Small',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'ac5B7wddCCkYMGLRWh8gb',
    name: 'Merfolk',
    initiativeType: 'roll',
    initiative: 1,
    hp: 11,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'vVo2GvMfVo4NciBtly8sP',
    name: 'Merrow',
    initiativeType: 'roll',
    initiative: 0,
    hp: 45,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'R7D1trM7HT65rtUxKl0OE',
    name: 'Mimic',
    initiativeType: 'roll',
    initiative: 1,
    hp: 58,
    size: 'Medium',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'y9Dick_LxVbT2dxpV_cJU',
    name: 'Minotaur',
    initiativeType: 'roll',
    initiative: 0,
    hp: 76,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'Ex3e98nE2lMTTTubQcio7',
    name: 'Mummy',
    initiativeType: 'roll',
    initiative: -1,
    hp: 58,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'FzPuMc4Qw4MdwuJM8QR3v',
    name: 'Mummy Lord',
    initiativeType: 'roll',
    initiative: 0,
    hp: 97,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'gQV2dsupHlweey-tyqDlV',
    name: 'Guardian Naga',
    initiativeType: 'roll',
    initiative: 4,
    hp: 127,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'i44-N8sksN-oF0XSpODN6',
    name: 'Spirit Naga',
    initiativeType: 'roll',
    initiative: 3,
    hp: 75,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: '_qIIegPFXRQ8IvKuWFwN2',
    name: 'Nightmare',
    initiativeType: 'roll',
    initiative: 2,
    hp: 68,
    size: 'Large',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'G0QzqVFPpNSfghmBIguN5',
    name: 'Ogre',
    initiativeType: 'roll',
    initiative: -1,
    hp: 59,
    size: 'Large',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'nOBO7WF34x0oPWm0kRdfa',
    name: 'Oni',
    initiativeType: 'roll',
    initiative: 0,
    hp: 110,
    size: 'Large',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'C1N64HKi1YVEBrRiFLQcf',
    name: 'Black Pudding',
    initiativeType: 'roll',
    initiative: -3,
    hp: 85,
    size: 'Large',
    category: 'Ooze',
    categoryIds: ['TmUkOJWKL53ZHQRchxI90'],
  },
  {
    id: '0PvyNUXXywtBNa1vRGxw5',
    name: 'Gelatinous Cube',
    initiativeType: 'roll',
    initiative: -4,
    hp: 84,
    size: 'Large',
    category: 'Ooze',
    categoryIds: ['TmUkOJWKL53ZHQRchxI90'],
  },
  {
    id: 'MKC68d-LDY_yZRd_Ry6Ak',
    name: 'Gray Ooze',
    initiativeType: 'roll',
    initiative: -2,
    hp: 22,
    size: 'Medium',
    category: 'Ooze',
    categoryIds: ['TmUkOJWKL53ZHQRchxI90'],
  },
  {
    id: '6jmbhmb2Zkj2mVLUYVFQY',
    name: 'Ochre Jelly',
    initiativeType: 'roll',
    initiative: -2,
    hp: 45,
    size: 'Large',
    category: 'Ooze',
    categoryIds: ['TmUkOJWKL53ZHQRchxI90'],
  },
  {
    id: 'Ub1HITmuTbRgv0yaWUNVE',
    name: 'Orc',
    initiativeType: 'roll',
    initiative: 1,
    hp: 15,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'BYuqnvVivfkHJmHYu65hK',
    name: 'Otyugh',
    initiativeType: 'roll',
    initiative: 0,
    hp: 114,
    size: 'Large',
    category: 'Aberration',
    categoryIds: ['hL6Lx5RYOj_ViMtZD2oI3'],
  },
  {
    id: 'vbfNJBGKjgm4kwozvas68',
    name: 'Owlbear',
    initiativeType: 'roll',
    initiative: 1,
    hp: 59,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'Hiqcdi1l9lk4Trbyq6f-2',
    name: 'Pegasus',
    initiativeType: 'roll',
    initiative: 2,
    hp: 59,
    size: 'Large',
    category: 'Celestial',
    categoryIds: ['aWqvZp9oborYGfWKSl8Uq'],
  },
  {
    id: 'J6pY8rVR6drb-sLoFxjGx',
    name: 'Pseudodragon',
    initiativeType: 'roll',
    initiative: 2,
    hp: 7,
    size: 'Tiny',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: '60MqLsFll5TBiXacmPuKK',
    name: 'Purple Worm',
    initiativeType: 'roll',
    initiative: -2,
    hp: 247,
    size: 'Gargantuan',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'XhCeWVBoF7JCudeyRg6JK',
    name: 'Rakshasa',
    initiativeType: 'roll',
    initiative: 3,
    hp: 110,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: 'T6C11DqBp1zxlmcPZQiv9',
    name: 'Remorhaz',
    initiativeType: 'roll',
    initiative: 1,
    hp: 195,
    size: 'Huge',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'PbSG3L-8PE-hGjR7_Do24',
    name: 'Roc',
    initiativeType: 'roll',
    initiative: 0,
    hp: 248,
    size: 'Gargantuan',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'EIkIsgtcIrbo9gHM4EtpU',
    name: 'Roper',
    initiativeType: 'roll',
    initiative: -1,
    hp: 93,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'ejyYMdTHbxSq_PUK5NExP',
    name: 'Rust Monster',
    initiativeType: 'roll',
    initiative: 1,
    hp: 27,
    size: 'Medium',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'z3sXNLLy24noQhOdd_i2c',
    name: 'Sahuagin',
    initiativeType: 'roll',
    initiative: 0,
    hp: 22,
    size: 'Medium',
    category: 'Humanoid',
    categoryIds: ['EXWRd4hOvn7xM-yKnRQ6g'],
  },
  {
    id: 'K8tCMV9SrZh0V03srvt5V',
    name: 'Salamander',
    initiativeType: 'roll',
    initiative: 2,
    hp: 90,
    size: 'Large',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'VGzFugeoaTumLNBy_PWU1',
    name: 'Satyr',
    initiativeType: 'roll',
    initiative: 3,
    hp: 31,
    size: 'Medium',
    category: 'Fey',
    categoryIds: ['2GxyUQ21MGpzXIb50xxko'],
  },
  {
    id: '3xaVSe3Mp5Nhno732jDQ9',
    name: 'Shadow',
    initiativeType: 'roll',
    initiative: 2,
    hp: 16,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'l9rGkcF-VAXmSuMZh3U-x',
    name: 'Shambling Mound',
    initiativeType: 'roll',
    initiative: -1,
    hp: 136,
    size: 'Large',
    category: 'Plant',
    categoryIds: ['CCPdjktUPMbqrwM6x7Z1B'],
  },
  {
    id: 'S7XL_cN2kTUhsyRnR-htK',
    name: 'Shield Guardian',
    initiativeType: 'roll',
    initiative: -1,
    hp: 142,
    size: 'Large',
    category: 'Construct',
    categoryIds: ['TcaCDBtOMx2az4FN6XCZI'],
  },
  {
    id: 'ZpeWq7kq9ocwVOC4CLDib',
    name: 'Skeleton',
    initiativeType: 'roll',
    initiative: 2,
    hp: 13,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: '50DgfBPx_M0xlVbJYJNgF',
    name: 'Minotaur Skeleton',
    initiativeType: 'roll',
    initiative: 0,
    hp: 67,
    size: 'Large',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'mrxpeoXffi2p1sDLQpnOS',
    name: 'Warhorse Skeleton',
    initiativeType: 'roll',
    initiative: 1,
    hp: 22,
    size: 'Large',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'poSwfHXy31e8qp5TJa437',
    name: 'Specter',
    initiativeType: 'roll',
    initiative: 2,
    hp: 22,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'Q8Hc5c8kwdWfrNZ0Abf_5',
    name: 'Androsphinx',
    initiativeType: 'roll',
    initiative: 0,
    hp: 199,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'j6H1s21sZvTNJ_AC0HJpC',
    name: 'Gynosphinx',
    initiativeType: 'roll',
    initiative: 2,
    hp: 136,
    size: 'Large',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: 'Id0OQuinbHbxgPrwkCWe_',
    name: 'Sprite',
    initiativeType: 'roll',
    initiative: 4,
    hp: 2,
    size: 'Tiny',
    category: 'Fey',
    categoryIds: ['2GxyUQ21MGpzXIb50xxko'],
  },
  {
    id: 'wG1dixtgMUE_T00gY26Uz',
    name: 'Stirge',
    initiativeType: 'roll',
    initiative: 3,
    hp: 2,
    size: 'Tiny',
    category: 'Beast',
    categoryIds: ['5Bp7ldzDgpP_OafAMj9pL'],
  },
  {
    id: 'v7C19Bzwg1B0Bn2zRS9_X',
    name: 'Succubus/Incubus',
    initiativeType: 'roll',
    initiative: 3,
    hp: 66,
    size: 'Medium',
    category: 'Fiend',
    categoryIds: ['21mAUDVaww1z9i0TK1Oz6'],
  },
  {
    id: '-L9skeA170i5Cv1oIDjKo',
    name: 'Tarrasque',
    initiativeType: 'roll',
    initiative: 0,
    hp: 676,
    size: 'Gargantuan',
    category: 'Monstrosity',
    categoryIds: ['aCeiGzo6saeHjJjWe01U5'],
  },
  {
    id: '9UVohQe0u0Nkvm24-vBsV',
    name: 'Treant',
    initiativeType: 'roll',
    initiative: -1,
    hp: 138,
    size: 'Huge',
    category: 'Plant',
    categoryIds: ['CCPdjktUPMbqrwM6x7Z1B'],
  },
  {
    id: 'dszVlWTlwXmJjUQH_aIsr',
    name: 'Troll',
    initiativeType: 'roll',
    initiative: 1,
    hp: 84,
    size: 'Large',
    category: 'Giant',
    categoryIds: ['XBzczZgZAjHXVCP3QjJ0m'],
  },
  {
    id: 'yeef663D3Yq04g4WfxkxF',
    name: 'Unicorn',
    initiativeType: 'roll',
    initiative: 2,
    hp: 67,
    size: 'Large',
    category: 'Celestial',
    categoryIds: ['aWqvZp9oborYGfWKSl8Uq'],
  },
  {
    id: 'SHxx3uyXrCT6rZW2MxT3i',
    name: 'Vampire',
    initiativeType: 'roll',
    initiative: 4,
    hp: 144,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'iOrJT49MdQMsqP1qO40EN',
    name: 'Vampire Spawn',
    initiativeType: 'roll',
    initiative: 3,
    hp: 82,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'S_8VZ8LPXs73sGF_Xjzq7',
    name: 'Wight',
    initiativeType: 'roll',
    initiative: 2,
    hp: 45,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'Sg0J66QG-6O7SO1BXxTU1',
    name: 'Will--o’--Wisp',
    initiativeType: 'roll',
    initiative: 9,
    hp: 22,
    size: 'Tiny',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'hB0EJu5CDti-39R5Im4Z8',
    name: 'Wraith',
    initiativeType: 'roll',
    initiative: 3,
    hp: 67,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'lvkRQqF2Hp22NyWHLthuw',
    name: 'Wyvern',
    initiativeType: 'roll',
    initiative: 0,
    hp: 110,
    size: 'Large',
    category: 'Dragon',
    categoryIds: ['fNTPf83CpbJUfOslXv9Dx'],
  },
  {
    id: 'V9jSEU2qtiSAYyPJZXkhe',
    name: 'Xorn',
    initiativeType: 'roll',
    initiative: 0,
    hp: 73,
    size: 'Medium',
    category: 'Elemental',
    categoryIds: ['oCoBXBAKnh3CqHQQ1P0i5'],
  },
  {
    id: 'pAZWnC-cvppwDJdgYRfQD',
    name: 'Zombie',
    initiativeType: 'roll',
    initiative: -2,
    hp: 22,
    size: 'Medium',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
  {
    id: 'm4ZToEJ9pIzVRGSWLfXNH',
    name: 'Ogre Zombie',
    initiativeType: 'roll',
    initiative: -2,
    hp: 85,
    size: 'Large',
    category: 'Undead',
    categoryIds: ['tZbowWTtyW9OA7jObqNru'],
  },
]
